### PR TITLE
I forgot to add the new algorith selection for the copy of specific playlist

### PR DESCRIPTION
**Pull request by Yoween**

### CODE REVIEW

**Comment by Yoween** [comment]
I think I fixed the wrong playlist order. Tell me what you thing about that because it may not be really optimized.

**Comment by Yoween** [comment]
I MESSED UP

**Comment by Yoween** [comment]
Okay I fixed it

**Comment by linsomniac** [comment]
> Also, the reason i changed `from . import backend` to `import backend` is because it juste doesn't work for me..

What are you running and what error do you get?

**Comment by Yoween** [comment]
> > Also, the reason i changed `from . import backend` to `import backend` is because it juste doesn't work for me..
> 
> What are you running and what error do you get?

Windows 11 64bit, Python 3.11.7 from website : 

Exception has occurred: ImportError
attempted relative import with no known parent package
  File "C:\Users\Yoween\Dev\spotify_to_ytmusic_gui\spotify2ytmusic\cli.py", line 7, in <module>
    from . import backend
ImportError: attempted relative import with no known parent package

**Comment by linsomniac** [comment]
I believe all items changed in this PR are addressed in the current main branch.

**Pull request closed without merging**
