### PR TITLE
Integrating Yoween's GUI.

### PR DESCRIPTION
**Pull request by linsomniac**
This is the integration of Yoween's GUI branch (as discussed in #15 and #19).

### CODE REVIEW

**Comment by Yoween** [comment]
nice, is the pip install working ?

**Comment by Yoween** [comment]
Hi, I fixed an important bug where i forgot to add the argument for the algorith, how can I push it to the project ?

**Comment by linsomniac** [comment]
Just have a fork that is off main, and commit the bug there and then click the "pull request" button, that's probably the easiest way to link it, and then I'll be happy to review and can manage the release process.

**Comment by linsomniac** [comment]
> nice, is the pip install working ?

I've been building the pip version, but I have not been testing it this weekend.  These versions that have been going out have been fairly experimental in that regard.  :-)

**Pull request merged**
