### PR TITLE
Syncing up projects

### PR DESCRIPTION
**Pull request by Yoween**
Hi, while I've modified you cli.py file, i think it's still usable as a command line tool. But you still may need to test everything.

If you think it's a good idea to use the same files and have both our projects merged together you can accept this pull request.

Otherwise it's fine and understandable. The point of your cli tool is to be lightweight and fast. The point of my gui tool it to be easy for a non tech savvy person to use it.

Have a good day !

### CODE REVIEW

**Comment by linsomniac** [comment]
I am open to unifying the code, I'll need to look at it in a little more depth than I have the time for over the next couple of days but I'll definitely take a look when I get a bit more time.  Thanks!  I saw your project a few days ago and linked to it from the README, and took a quick look at it.  Thanks for working on that, that's fantastic!

**Comment by Yoween** [comment]
Cool! There are still some things I want to change and my code needs a bit of refactoring too, but I'm glad you find my work useful!

**Comment by linsomniac** [comment]
Sorry I haven't had time to work on this, but I am still very interested in joining forces on this.  I did just add the last piece of outstanding code changes I had in the pipeline: the liked album load.  I'm afraid that restructured some of the internals, I'm not sure yet if this will impact your fork.  I hope to have some time to look at this further over the next week and get these two synced up.  Just wanted to give you a status.

**Comment by Yoween** [comment]
Hi, thank you for the update ! I am currently updating my fork to your latest commit. I think I'll just use your cli.py and restore the changed I've made, so no worries !

**Comment by Yoween** [comment]
I just looked at your code, and it seems like the functions `load_liked_albums` and `create_album` are not use anywhere. Am I missing something ?

**Comment by Yoween** [comment]
I just updated the cli.py file to be usable with your version. I checked some stuff that seems to be working fine. 
The only thing changed in the way it works it that now you need to provie input and output fies using `-i <input_file> -o <output_file>` instead of `<input_file> <output_file>`

**Comment by linsomniac** [comment]
> I just looked at your code, and it seems like the functions `load_liked_albums` and `create_album` are not use anywhere. Am I missing something ?

Do you mean "create_playlist" instead of "create_album"?  load_liked_albums is defined as an entrypoint in the pyproject.toml file:

```
[tool.poetry.scripts]
s2yt_load_liked = "spotify2ytmusic.cli:load_liked"
s2yt_load_liked_albums = "spotify2ytmusic.cli:load_liked_albums"
s2yt_copy_playlist = "spotify2ytmusic.cli:copy_playlist"
s2yt_copy_all_playlists = "spotify2ytmusic.cli:copy_all_playlists"
s2yt_create_playlist = "spotify2ytmusic.cli:create_playlist"
s2yt_list_playlists = "spotify2ytmusic.cli:list_playlists"
s2yt_search = "spotify2ytmusic.cli:search"
s2yt_list_liked_albums = "spotify2ytmusic.cli:list_liked_albums"
```

So these all become CLI programs that can be used.

Sorry for the late reply, this week has been really busy.

**Comment by linsomniac** [comment]
I don't have much time to work on this tonight, but I did start taking a look at your cli.py, and the changes you made in create_playlist().  I have an idea for a different way of going about that which I think will be cleaner in the long-run.

I've started an "integration" branch to work on bringing these two projects together.  See the changes I just committed there, it's a work in progress and I've only done the conversion of create_playlist() so far (and some associated components).

The idea: I'm creating a "backend.py" that has the "create_playlist(pl_name)" function in it, which only creates the playlist.  In cli.py I changed the create_playlist() function to look at the CLI arguments and get the playlist name, and then calls backend.create_playlist(pl_name).  The GUI then will be able to call backend.create_playlist as well, without having to "turn off argument parsing".  This also allows the cli to switch to something like typer (which I am thinking about), without interfering with the GUI.

Then I'm thinking that we'll have gui.py in there, but the entry point will be from "cli.py" as "gui" or something, so it'd sprout another command like "s2yt_gui".

I'll continue working on this as I have time.

Thoughts?

**Comment by Yoween** [comment]
Okay I see, that's a really smart approach! I'll be adapting the gui code for these changes.

**Comment by linsomniac** [comment]
Make sure to branch off this "integration" branch and if you make progress on it drop a PR and I'll work in that as well, so you can "merge upstream" and we can stay in sync.

**Comment by Yoween** [comment]
Hey! I can't find the backend.py file. I doesn't seem to appear in the 'integration' branch

**Comment by linsomniac** [comment]
Oops, I forgot to git add it.  Pushed.

**Comment by Yoween** [comment]
Also, I've noticed you use 'from . import <>', which doesn't work for me, so I'm using regular 'import <>'. Any reason why you use this method?

**Comment by Yoween** [comment]
I've added an 'algo' argument for lookup_song() and copier(), which lets the user select one of our three algorithms. What's your opinion on this ?

**Comment by Yoween** [comment]
Also created a lookup_playlist(), that replaces a bit of code you use twice in your code.

**Comment by linsomniac** [comment]
I just finished an initial conversion of the cli.py into cli.py+backend.py, but I haven't done any testing of it.

I approve of the "algo" argument, though I'd probably call it "yt_search_algorithm" or something, just to make the code a bit more self-documenting.  I had always intended to augment or improve or parameterize the search algorithm, but in my initial use the simpler algorithm worked so I never pursued it further.

**Comment by linsomniac** [comment]
Do you have a PR of those changes against the integration branch?

**Comment by Yoween** [comment]
My bad I actually forgot to do it... I'm in bed now but I'll do it when I wake up tomorrow

**Pull request closed without merging**
